messages:
    load: "%filename% has been loaded."
    
    # Setting this to true will disable the load message
    disable_message: false
    
    # Placeholders
    # %filename% - Schematic file name
    