name: SchematicUtility
main: com.sm10259.su.SchematicUtility
version: 1.1
api-version: 1.14
author: Sarah Myerson
website: sarahmyerson.com
Description: WorldEdit schematic manager
depend: [WorldEdit]

load: STARTUP

commands:
    su:
        description: SchematicUtility plugin mangement